---
title: "NY NOAA Graphs"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}

data("ny_noaa")

noaa_df = ny_noaa %>% sample_n(10000) %>% 
  mutate(month = months.Date(date, abbreviate = TRUE),
         day = chron::days(date),
         year = chron::years(date),
         tmax = (as.numeric(tmax))/10,
         tmin = (as.numeric(tmin))/10,
         prcp = prcp/10)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

weather = noaa_df %>% 
  filter(month %in% c("Jan", "Jul")) %>% 
  ggplot(aes(x = year, y = tmax, color = month)) +
  facet_grid(~month) +
  geom_boxplot() +
  labs(
  title = "A two-panel plot showing the average max temperature in January and in July in each station across years") +
  theme(legend.position = "none", 
        axis.text.x = element_text(angle = 45, hjust = 1, size = 5))

ggplotly(weather)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
my_hex = ggplot(noaa_df, aes(x = tmin, y = tmax)) +
  geom_hex(aes()) +
  labs(
  title = "A plot showing  tmax vs tmin for the full dataset") +
  theme(legend.position = "left")

ggplotly(my_hex)
```

### Chart C

```{r}
my_boxes = noaa_df %>% 
  filter(snow > 0 & snow < 100) %>% 
  ggplot(aes(x = year, y = snow, fill = year)) +
  geom_boxplot(alpha = 0.3) +
  labs(
  title = "A plot showing the distribution of snowfall values greater than 0 and less than 100 separately by year") +
  theme(legend.position = "none", 
        axis.text.x = element_text(angle = 45, hjust = 1, size = 7))

ggplotly(my_boxes)
```

